language: generic
sudo: false
cache: apt

env: DEPLOY_FILE="$TRAVIS_BUILD_DIR/../tackup-$TRAVIS_TAG.xpi"
addons:
  apt:
    packages:
      - zip
    sources:
      - r-packages-trusty

after_success:
  - if [ "$TRAVIS_TAG" ]; then
      zip -x .git -r9 "$DEPLOY_FILE" *;
    fi

deploy:
  provider: releases
  api-key:
    secure: A+D6CRPqRNVSBOuBx6cvv6E+dd6w2jWROG5V4ANc9cxNQNdE+gqk8ZA9yNGFxpyH9Xl27zNIN/PZ8bMUaus+A3eeEq3t2ytQNLFLWQxiR2UAlXkwhd94CuKU/2SsWrv05F3KGBbI/NteC57YEI1921//ZOiFSAfG0q/gJS2ZVFTzDmP3NVb5InMz0SRhCuT2ad+EYKSBFAU5hn1fPKtqX/x4EYMgIRmZRKmLoJU6ipWg9+lGwCvTkicLykePsjKXrw8hS00G2Fo91Cij0ZGq8RDHWEcneBQHVzJF1H+PjdycypmqgWgFvTODJC+QKIn45/EPyIQeXNrMZhV0+yXyHJVUd7v+hl1+uHetGzXI20lm+f2t+A66Kk6Dz+chVwpn+9eI+tw4cvLDP1bCVQvr1jDxS3USR2PZSix/RwEJqiKbI67UvzKPCwIB3HASwII9UrWHD8Xjc8OvKKn/6dUb9CPObLdMFs1SpwqUk9WXY3vnIESccXJjYD2F3KX89yrRUvkPF56ZVEmThhGqUsxg+lz2UyN5Wj0Twqa0M2+uN8c26k79hCuFRUpwBwra9/TZczOlYZunF90L4GChvYqhemYf/4Oue63xi8e0geBwSjBiSyXvyZna6qoclknPF0WWTj5Ga8Aka9Bue3ugQ38Fg5oFoI4lM14oW++3/xu+FQE=
  file: "$DEPLOY_FILE"
  skip_cleanup: true
  on:
    tags: true
